refactor : artifact에서 jar 다운로드 정상 여부 검증 로직 작성

diff --git a/.github/workflows/cd-gradle.yml b/.github/workflows/cd-gradle.yml
--- a/.github/workflows/cd-gradle.yml
+++ b/.github/workflows/cd-gradle.yml
@@ -23,21 +23,34 @@ jobs:
       - name: Download Build Artifact
         uses: actions/download-artifact@v3
         with:
-          name: spring-boot-artifact  # CI에서 업로드한 아티팩트 이름
+          name: spring-boot-artifact
 
+      # 다운로드된 아티팩트 확인
+      - name: Verify Artifact
+        run: |
+          ls -alh
+          # 아티팩트 파일이 있는지 확인
+          if [ ! -f "./daily-mission-api-server-0.0.1-SNAPSHOT.jar" ]; then
+            echo "Artifact not found!";
+            exit 1;
+          fi
+
+      # Docker Login
       - name: Docker Login
         uses: docker/login-action@v2.2.0
         with:
           username: ${{ secrets.DOCKER_USERNAME }}
           password: ${{ secrets.DOCKER_PASSWORD }}
 
+      # Docker Image Build 및 Push
       - name: Build and Push Docker Image
         uses: docker/build-push-action@v4.1.1
         with:
-          context: .
+          context: .  # 컨텍스트는 현재 디렉토리로 설정 (다운로드한 아티팩트가 현재 디렉토리에 있어야 함)
           push: true
           tags: ${{ secrets.DOCKER_USERNAME }}/spring-boot-server
 
+      # EC2에 배포
       - name: Deploy to AWS EC2
         uses: appleboy/ssh-action@v0.1.10
         with:
@@ -47,7 +60,7 @@ jobs:
           script: |
             # 다운로드된 아티팩트 확인
             ls -alh
-
+            # Docker Pull 및 EC2에 배포
             docker pull ${{ secrets.DOCKER_USERNAME }}/spring-boot-server
             docker stop $(docker ps -a -q) || true
             docker run -d --log-driver=syslog -p 8080:8080 ${{ secrets.DOCKER_USERNAME }}/spring-boot-server
